// Create variables for each time-block (9AM-5PM)

var userInput01 = document.getElementById("block01")
var userInput02 = document.getElementById("block02")
var userInput03 = document.getElementById("block03")
var userInput04 = document.getElementById("block04")
var userInput05 = document.getElementById("block05")
var userInput06 = document.getElementById("block06")
var userInput07 = document.getElementById("block07")
var userInput08 = document.getElementById("block08")
var userInput09 = document.getElementById("block09")

localStorage.setItem("block01", userInput01)
localStorage.setItem("block02", userInput02)
localStorage.setItem("block03", userInput03)
localStorage.setItem("block04", userInput04)
localStorage.setItem("block05", userInput05)
localStorage.setItem("block06", userInput06)
localStorage.setItem("block07", userInput07)
localStorage.setItem("block08", userInput08)
localStorage.setItem("block09", userInput09)
